version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing dependencies..."
      - rsync -a NewTest/ NewTest/lib/
      - pip install -r NewTest/requirements.txt -t NewTest/lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd NewTest/lib
      - ls
      - pwd
      - zip -r9 ../NewTest.zip .
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name NewTest --zip-file fileb://NewTest.zip
      - echo "DONE!!"
