version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing dependencies..."
      - pip install -r NewTest/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - ls
      - pwd
      - zip -r9 ../NewTest.zip .
      - cd ..
      - zip -g NewTest.zip /lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name NewTest --zip-file fileb://NewTest.zip
      - echo "DONE!!"
